name: Build executables

on:
  workflow_dispatch: # Manually triggered event
  pull_request: # Trigger the workflow on push or pull request,

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Windows executable with pyinstaller
        run: |
          pyinstaller h4xtools.py --add-data "resources/*;resources" --onefile -F --clean
      - name: Calculate MD5 hash
        run: |
          md5sum dist/h4xtools.exe > dist/h4xtools.exe.md5
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: dist/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: $GITHUB_REF_NAME
          body: |
            Windows Executable: [${GITHUB_REF_NAME}](https://github.com/${GITHUB_REPO}/releases/download/${GITHUB_REF_NAME}/h4xtools.exe)
            MD5 Hash: $(cat dist/h4xtools.exe.md5)
          allowUpdates: true
          makeLatest: true

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Linux executable with pyinstaller
        run: |
          pyinstaller h4xtools.py --add-data "resources/*:resources" --onefile -F --clean
      - name: Calculate MD5 hash
        run: |
          md5sum dist/h4xtools > dist/h4xtools.md5
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux Executable
          path: dist/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: $GITHUB_REF_NAME
          body: |
            Linux Executable: [${GITHUB_REF_NAME}](https://github.com/${GITHUB_REPO}/releases/download/${GITHUB_REF_NAME}/h4xtools)
            MD5 Hash: $(cat dist/h4xtools.md5)
          allowUpdates: true
          makeLatest: true